[package]
name = "extract-pps"
version = "0.1.0"
authors = ["DanieÌˆl de Kok <me@danieldk.eu>"]

[dependencies]
conllx = { path = "../conllx-rs" }
getopts = "0.2"
lazy_static = "0.2"
maplit = "0.1"
petgraph = "0.2"